com.griddynamics.es.graduation.project:
  esHost: ${ES_HOST:http://localhost:9200}
  user: ${ES_USER:}
  pass: ${ES_PASS:}
  index: ${ES_INDEX:typeaheads}

  files:
    mappings: classpath:elastic/typeaheads/mappings.json
    settings: classpath:elastic/typeaheads/settings.json
    bulkData: classpath:elastic/typeaheads/bulk_data.txt

  request:
    default:
      findByQuerySize: 10
      getAllSize: 50
    minQueryLength: 3
    fuzziness:
      startsFromLength:
        one: 4
        two: 6
      boost:
        zero: 1.0
        one: 0.5
        two: 0.25
    prefixQueryBoost: 0.9